# Copyright (C) 2010-2011 Aloysius Indrayanto
#                         AnemoneSoft.com

# Makefile.config

JAVA         = java
JAVAC        = javac
JAR          = jar
JARSIGNER    = jarsigner

CLASSPATH    = .

APP_JAR_FILE = vma.jar
APP_JRX_FILE = vma_x.jar
APP_PRO_FILE = vma.pro
APP_MAP_FILE = vma.map

# -encoding UTF-8 -g:none -Xlint:deprecation -Xlint:unchecked

# keytool -genkey -alias VMAApplet -keystore VMAApplet.jks -keyalg RSA -keysize 2048 -validity 3600 -dname "CN=VMA Solutions,OU=AnemoneSoft.com,O=AnemoneSoft.com,L=Surabaya,ST=East Java,C=ID correct" -keypass abc123 -storepass abc123

#
# openssl genrsa -des3 -out ca.key 2048
# openssl req -new -x509 -days 3600 -key ca.key -out ca.cer
#
# keytool -genkey -alias VMAApplet -keyalg RSA -keystore VMAApplet.jks -keysize 2048 -validity 3600
# keytool -certreq -alias VMAApplet -keystore VMAApplet.jks -file VMAApplet.csr
#
# openssl ca -policy policy_anything -cert ca.cer -keyfile ca.key -days 360 -in VMAApplet.csr -out VMAApplet.cer
#
# keytool -import -trustcacerts -alias root -file ca.cer -keystore VMAApplet.jks
# keytool -import -trustcacerts -alias VMAApplet -file VMAApplet.cer -keystore VMAApplet.jks
#

