# Copyright (C) 2010-2011 Aloysius Indrayanto
#                         AnemoneSoft.com

# anemonesoft/lic/Makefile

include ../../Makefile.config
include ../../Makefile.utils

CLASSPATH  = ../..
LIB_SOURCE = Licensing.class

default: $(LIB_SOURCE)
	@echo > /dev/null
