# Copyright (C) 2010-2022 Aloysius Indrayanto
#                         AnemoneSoft.com

# appwrapper/Makefile

include ../Makefile.config
include ../Makefile.utils

CLASSPATH  = ..
APP_SOURCE = AppMain.class          \
             SimpleAppletStub.class

default: $(APP_SOURCE)
	@echo > /dev/null
