# Copyright (C) 2010-2011 Aloysius Indrayanto
#                         AnemoneSoft.com

# anemonesoft/Makefile

default:
	@$(MAKE) -s -C i18n default
	@$(MAKE) -s -C stat default
	@$(MAKE) -s -C plot default
	@$(MAKE) -s -C gui  default
	@$(MAKE) -s -C lic  default

clean:
	@$(MAKE) -s -C i18n clean
	@$(MAKE) -s -C stat clean
	@$(MAKE) -s -C plot clean
	@$(MAKE) -s -C gui  clean
	@$(MAKE) -s -C lic  clean
