# Copyright (C) 2010-2011 Aloysius Indrayanto
#                         AnemoneSoft.com

# appzgl/Makefile

include ../Makefile.config
include ../Makefile.utils

CLASSPATH  = ..
APP_SOURCE = GenLicApp.class \
             GenLic.class

default: $(APP_SOURCE)
	@echo > /dev/null
