# Copyright (C) 2010-2022 Aloysius Indrayanto
#                         AnemoneSoft.com

# anemonesoft/plot/Makefile

include ../../Makefile.config
include ../../Makefile.utils

CLASSPATH  = ../..
LIB_SOURCE = PlotRenderer.class \
             Region.class

default: $(LIB_SOURCE)
	@echo > /dev/null
