# Copyright (C) 2010-2011 Aloysius Indrayanto
#                         AnemoneSoft.com

# anemonesoft/stat/Makefile

include ../../Makefile.config
include ../../Makefile.utils

CLASSPATH  = ../..
LIB_SOURCE = BoxWhisker.class            \
             SUtil.class                 \
             Chromatogram.class          \
             DistTable.class             \
             FirstOrderRegression.class  \
             SecondOrderRegression.class \
             ThirdOrderRegression.class  \
             FourthOrderRegression.class \
             FifthOrderRegression.class  \
             MandelTest.class            \
             Homogeneity.class           \
             Accuracy.class              \
             PrecisionRSD.class          \
             PrecisionOWANO.class        \
             APGonzales.class            \
             APRozet.class               \
             Robustness.class            \
             QCShewhart.class

default: $(LIB_SOURCE)
	@echo > /dev/null
