# Copyright (C) 2010-2022 Aloysius Indrayanto
#                         AnemoneSoft.com

# anemonesoft/i18n/Makefile

include ../../Makefile.config
include ../../Makefile.utils

CLASSPATH  = ../..
LIB_SOURCE = StringTranslator.class

default: $(LIB_SOURCE)
	@echo > /dev/null
